# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'OpenPlayer' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
  pod 'Masonry', '1.1.0'
  pod 'OpenCV', '4.3.0'
  pod 'GPUImage', '0.1.7'
  pod 'LibTorch', '2.1.0'
end
